"use client";

import { useState, useEffect, useRef } from "react";
import { ShieldCheck, AlertTriangle, FileText, Building2, User, IndianRupee, Calendar, Package, Hash } from "lucide-react";

interface VerifyData {
  invoiceNumber: string;
  invoiceType: string;
  date: string;
  dueDate: string;
  status: string;
  firm: { name: string; gstin: string; address: string; city: string; state: string; phone: string };
  customer: { name: string; gstin: string; address: string; city: string; state: string; phone: string };
  items: { name: string; hsn: string; quantity: number; rate: number; amount: number; gstRate: number; gstAmount: number }[];
  subtotal: number;
  totalTax: number;
  grandTotal: number;
  amountPaid: number;
  amountInWords: string;
  createdAt: string;
}

function formatCurrency(n: number) {
  return new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 2 }).format(n);
}

function formatDate(d: string) {
  if (!d) return "-";
  return new Date(d).toLocaleDateString("en-IN", { day: "2-digit", month: "short", year: "numeric" });
}

const TYPE_LABELS: Record<string, string> = {
  tax_invoice: "Tax Invoice",
  bill_of_supply: "Bill of Supply",
  credit_note: "Credit Note",
  debit_note: "Debit Note",
  proforma: "Proforma Invoice",
  quotation: "Quotation",
  delivery_challan: "Delivery Challan",
  purchase_bill: "Purchase Bill",
  payment_receipt: "Payment Receipt",
  export_invoice: "Export Invoice",
};

export default function VerifyPage() {
  const [data, setData] = useState<VerifyData | null>(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const didFetch = useRef(false);

  useEffect(() => {
    if (didFetch.current) return;
    didFetch.current = true;

    const params = new URLSearchParams(window.location.search);
    const id = params.get("id");
    const uid = params.get("uid");

    if (!id || !uid) {
      setError("Invalid verification link. Missing invoice ID or user ID.");
      setLoading(false);
      return;
    }

    fetch(`/api/verify-invoice?id=${id}&uid=${uid}`)
      .then((r) => r.json())
      .then((res) => {
        if (res.error) {
          setError(res.error === "Invoice not found" ? "Invoice not found. It may have been deleted or the link is invalid." : res.error);
        } else {
          setData(res.data);
        }
      })
      .catch(() => setError("Failed to verify invoice. Please try again later."))
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-emerald-50 flex items-center justify-center">
        <div className="animate-spin w-10 h-10 border-4 border-blue-500 border-t-transparent rounded-full" />
      </div>
    );
  }

  if (error) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-red-50 via-white to-orange-50 flex items-center justify-center p-4">
        <div className="bg-white rounded-2xl shadow-xl p-8 max-w-md w-full text-center">
          <AlertTriangle className="w-16 h-16 text-red-500 mx-auto mb-4" />
          <h1 className="text-xl font-bold text-gray-900 mb-2">Verification Failed</h1>
          <p className="text-gray-500 text-sm">{error}</p>
          <a href="/" className="mt-6 inline-block px-6 py-2 bg-blue-600 text-white rounded-lg text-sm font-medium hover:bg-blue-700">Go to Home</a>
        </div>
      </div>
    );
  }

  if (!data) return null;

  const balance = data.grandTotal - data.amountPaid;

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 via-white to-emerald-50 p-4 md:p-8">
      <div className="max-w-2xl mx-auto">
        {/* Verified Badge */}
        <div className="bg-emerald-600 text-white rounded-2xl p-6 mb-6 flex items-center gap-4 shadow-lg">
          <ShieldCheck className="w-12 h-12 flex-shrink-0" />
          <div>
            <h1 className="text-xl font-bold">Invoice Verified</h1>
            <p className="text-emerald-100 text-sm mt-1">This invoice was generated by GST Bill Manager and is authentic.</p>
          </div>
        </div>

        {/* Invoice Info */}
        <div className="bg-white rounded-2xl shadow-md border p-6 mb-4">
          <div className="flex items-center gap-2 mb-4">
            <FileText className="w-5 h-5 text-blue-600" />
            <h2 className="font-bold text-gray-900">Invoice Details</h2>
          </div>
          <div className="grid grid-cols-2 gap-3 text-sm">
            <div><span className="text-gray-400 text-xs block">Invoice Number</span><span className="font-bold text-gray-900">{data.invoiceNumber}</span></div>
            <div><span className="text-gray-400 text-xs block">Type</span><span className="font-medium text-gray-700">{TYPE_LABELS[data.invoiceType] || data.invoiceType}</span></div>
            <div><span className="text-gray-400 text-xs block">Date</span><span className="font-medium text-gray-700">{formatDate(data.date)}</span></div>
            <div><span className="text-gray-400 text-xs block">Due Date</span><span className="font-medium text-gray-700">{formatDate(data.dueDate)}</span></div>
            <div><span className="text-gray-400 text-xs block">Status</span>
              <span className={`inline-block px-2 py-0.5 rounded-full text-xs font-bold ${data.status === "paid" ? "bg-emerald-100 text-emerald-700" : data.status === "overdue" ? "bg-red-100 text-red-700" : "bg-amber-100 text-amber-700"}`}>{data.status.toUpperCase()}</span>
            </div>
            <div><span className="text-gray-400 text-xs block">Created</span><span className="text-gray-600 text-xs">{formatDate(data.createdAt)}</span></div>
          </div>
        </div>

        {/* Seller / Buyer */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          <div className="bg-white rounded-2xl shadow-md border p-5">
            <div className="flex items-center gap-2 mb-3"><Building2 className="w-4 h-4 text-blue-600" /><h3 className="font-bold text-sm text-gray-900">Seller (From)</h3></div>
            <p className="font-bold text-sm">{data.firm.name}</p>
            {data.firm.gstin && <p className="text-xs text-blue-600 font-mono mt-1">GSTIN: {data.firm.gstin}</p>}
            <p className="text-xs text-gray-500 mt-1">{[data.firm.address, data.firm.city, data.firm.state].filter(Boolean).join(", ")}</p>
            {data.firm.phone && <p className="text-xs text-gray-500">Ph: {data.firm.phone}</p>}
          </div>
          <div className="bg-white rounded-2xl shadow-md border p-5">
            <div className="flex items-center gap-2 mb-3"><User className="w-4 h-4 text-emerald-600" /><h3 className="font-bold text-sm text-gray-900">Buyer (To)</h3></div>
            <p className="font-bold text-sm">{data.customer.name}</p>
            {data.customer.gstin && <p className="text-xs text-emerald-600 font-mono mt-1">GSTIN: {data.customer.gstin}</p>}
            <p className="text-xs text-gray-500 mt-1">{[data.customer.address, data.customer.city, data.customer.state].filter(Boolean).join(", ")}</p>
            {data.customer.phone && <p className="text-xs text-gray-500">Ph: {data.customer.phone}</p>}
          </div>
        </div>

        {/* Items */}
        <div className="bg-white rounded-2xl shadow-md border p-5 mb-4">
          <div className="flex items-center gap-2 mb-3"><Package className="w-4 h-4 text-violet-600" /><h3 className="font-bold text-sm text-gray-900">Items ({data.items.length})</h3></div>
          <div className="overflow-x-auto">
            <table className="w-full text-xs">
              <thead>
                <tr className="border-b text-gray-500 text-left">
                  <th className="pb-2 pr-2">#</th>
                  <th className="pb-2 pr-2">Item</th>
                  <th className="pb-2 pr-2">HSN</th>
                  <th className="pb-2 pr-2 text-right">Qty</th>
                  <th className="pb-2 pr-2 text-right">Rate</th>
                  <th className="pb-2 pr-2 text-right">GST%</th>
                  <th className="pb-2 text-right">Amount</th>
                </tr>
              </thead>
              <tbody>
                {data.items.map((item, i) => (
                  <tr key={i} className="border-b border-gray-100">
                    <td className="py-2 pr-2 text-gray-400">{i + 1}</td>
                    <td className="py-2 pr-2 font-medium text-gray-900">{item.name}</td>
                    <td className="py-2 pr-2 text-gray-500 font-mono">{item.hsn || "-"}</td>
                    <td className="py-2 pr-2 text-right">{item.quantity}</td>
                    <td className="py-2 pr-2 text-right">{formatCurrency(item.rate)}</td>
                    <td className="py-2 pr-2 text-right">{item.gstRate}%</td>
                    <td className="py-2 text-right font-bold">{formatCurrency(item.amount + item.gstAmount)}</td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </div>

        {/* Totals */}
        <div className="bg-white rounded-2xl shadow-md border p-5 mb-4">
          <div className="flex items-center gap-2 mb-3"><IndianRupee className="w-4 h-4 text-orange-600" /><h3 className="font-bold text-sm text-gray-900">Amount Summary</h3></div>
          <div className="space-y-2 text-sm">
            <div className="flex justify-between"><span className="text-gray-500">Subtotal</span><span className="font-medium">{formatCurrency(data.subtotal)}</span></div>
            <div className="flex justify-between"><span className="text-gray-500">Tax (GST)</span><span className="font-medium">{formatCurrency(data.totalTax)}</span></div>
            <div className="flex justify-between border-t pt-2 border-gray-200"><span className="font-bold text-gray-900">Grand Total</span><span className="font-bold text-lg text-blue-700">{formatCurrency(data.grandTotal)}</span></div>
            {data.amountPaid > 0 && (
              <>
                <div className="flex justify-between"><span className="text-gray-500">Amount Paid</span><span className="font-medium text-emerald-600">{formatCurrency(data.amountPaid)}</span></div>
                {balance > 0 && <div className="flex justify-between"><span className="text-gray-500">Balance Due</span><span className="font-bold text-red-600">{formatCurrency(balance)}</span></div>}
              </>
            )}
          </div>
          {data.amountInWords && (
            <p className="mt-3 text-xs text-gray-500 italic border-t pt-2">Amount in words: {data.amountInWords}</p>
          )}
        </div>

        {/* Footer */}
        <div className="text-center text-xs text-gray-400 mt-6">
          <p>Verified by <a href="https://gstbillmanager.com" className="text-blue-500 font-medium hover:underline">GST Bill Manager</a></p>
          <p className="mt-1">This is a computer generated verification. E. & O.E.</p>
        </div>
      </div>
    </div>
  );
}
